name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Enable web
      run: flutter config --enable-web
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build web
      run: flutter build web --release --verbose
    
    - name: Check build output
      run: |
        echo "Checking if build/web directory exists..."
        ls -la build/
        echo "Checking if flutter.js exists..."
        ls -la build/web/
        echo "Checking if main.dart.js exists..."
        ls -la build/web/ | grep -E "(flutter|main|index)"
        echo "Checking Flutter version..."
        flutter --version
        echo "Cleaning and rebuilding..."
        flutter clean
        flutter build web --release
        echo "Final check after rebuild..."
        ls -la build/web/
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/web'
    
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4